import marimo

__generated_with = "0.22.0"
app = marimo.App(width="medium")

with app.setup:
    import marimo as mo
    import polars as pl


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    # 1. Define selected keywords
    """)
    return


@app.cell(hide_code=True)
def _():
    # List 1 – Agents, SWE & Software Engineering
    kw_1 = [
        "agent",
        "agent benchmark",
        "agent composition",
        "agent design",
        "agent discovery",
        "agent diversity",
        "agent ensemble learning",
        "agent evaluation",
        "agent framework",
        "agent memory",
        "agent reasoning",
        "agent reliability",
        "agent safety",
        "agent simulation",
        "agent society",
        "agent specialization",
        "agent system",
        "agent tool use",
        "agent training",
        "agent-awareness",
        "agent-based simulation",
        "agent-centric benchmark",
        "agent-to-agent protocol",
        "agentic",
        "agentic ai",
        "agentic augmentation",
        "agentic coding",
        "agentic collaboration",
        "agentic data synthesis",
        "agentic framwork",
        "agentic learning",
        "agentic llm",
        "agentic misalignment",
        "agentic multi-turn reasoning",
        "agentic multimodal model",
        "agentic rag",
        "agentic reasoning",
        "agentic reinforcement learning",
        "agentic rl",
        "agentic search",
        "agentic serving",
        "agentic simulation",
        "agentic system",
        "agentic systems",
        "agentic task",
        "agentic training",
        "agentic workflow",
        "agentic workflows",
        "agentless",
        "agents",
        "agents with memory",
        "ai agent",
        "ai agents",
        "app agent",
        "automated code repair",
        "autonomous agent",
        "autonomous agents",
        "benchmarks for agents",
        "browser-use agent",
        "chart-to-code generation",
        "code agent",
        "code generation",
        "code synthesis",
        "coding agent",
        "coding agent benchmark",
        "coding agents",
        "computer use",
        "computer use agent",
        "computer use agents",
        "computer use-agent",
        "computer-use agent",
        "computer-use agents",
        "computer-using agent",
        "computer-using agents",
        "constraint-aware tool use",
        "cooperative multi-agent rl",
        "cuda code generation",
        "data agent",
        "data science agents",
        "database agents",
        "deep research agent",
        "deep search agent",
        "digital agents",
        "doctor agent",
        "earth-agent",
        "embodied agent",
        "embodied agents",
        "function calling",
        "generalist agent",
        "generative agents",
        "geometry agent prover",
        "gui agent",
        "gui agent safety",
        "gui agents",
        "heterogeneous agent reinforcement learning",
        "heterogeneous agents",
        "human debugging",
        "human-agent cooperation",
        "human-agent interaction",
        "inter-agent communication",
        "language agent",
        "language agents",
        "language model agents",
        "large language models for code generation",
        "llm agent",
        "llm agents",
        "llm based agent",
        "llm search agents",
        "llm tool use",
        "llm-based agent",
        "llm-based agent systems",
        "llm-based agents",
        "llm/vlm agent",
        "lm agent",
        "long-horizon agent",
        "long-horizon agents",
        "medical agent",
        "medical agents",
        "memory agents benchmark",
        "mobile agent",
        "mobile agents",
        "mobile gui agent",
        "mobile-agent",
        "model debugging",
        "multi agent",
        "multi agent reinforcement learning",
        "multi agent system",
        "multi agent systems",
        "multi-agent",
        "multi-agent collaboration",
        "multi-agent communication",
        "multi-agent coordination",
        "multi-agent debate",
        "multi-agent discussion",
        "multi-agent framework",
        "multi-agent imitation learning",
        "multi-agent llm",
        "multi-agent llm systems",
        "multi-agent llms",
        "multi-agent optimization",
        "multi-agent orchestration",
        "multi-agent react",
        "multi-agent reinforcement learning",
        "multi-agent simulation",
        "multi-agent system",
        "multi-agent systems",
        "multi-agent systems (mas)",
        "multi-agent system，large language model，evidence-based reasoning",
        "multi-agent traffic simulation",
        "multi-modal agent",
        "multi-modal embodied agent",
        "multi-modal large language agent",
        "multi-social-agent self-distillation",
        "multi-turn tool use",
        "multiagent systems",
        "multimodal agent",
        "multimodal agents",
        "multimodal code generation",
        "neural program synthesis",
        "neurosymbolic agent",
        "proactive agent",
        "proactive agents",
        "program synthesis",
        "real-world github issues",
        "reasoning scaffolding",
        "rebuttal agent",
        "repository generation",
        "research agents",
        "robotic tool use",
        "role-playing character agent",
        "role-playing language agents",
        "runtime code execution",
        "safe multi-agent reinforcement learning",
        "scalable tool use",
        "science agents",
        "search agent",
        "secure code generation",
        "self-evolving agent",
        "software engineering",
        "spatial agent",
        "swe agent",
        "swe-agent",
        "tool agent",
        "tool use",
        "tool use evaluation",
        "tool-augmented agents",
        "tool-augmented llms",
        "tool-augmented lms",
        "tool-augmented reasoning",
        "tool-use",
        "tool-use alignment",
        "tool-use large language model",
        "tool-using agent",
        "verifiable code generation",
        "verifiable coding agents",
        "videoagenttrek",
        "vision centric agents",
        "vlm agent",
        "web agent",
        "web agents",
        "webagent",
        "Static analysis",
        "Continous integration",
        "Test case generation",
        "Code search",
        "Compiler",
        "Complier optimisation",
    ]
    kw_1 = [kw.lower() for kw in kw_1]
    len(kw_1)
    return (kw_1,)


@app.cell(hide_code=True)
def _():
    # List 2 – Reinforcement Learning & Post-training
    kw_2 = [
        "action free offline to online reinforcement learning",
        "actor-critic",
        "adversarial imitation learning",
        "adversarial reward learning",
        "adversarial rl",
        "agentic reinforcement learning",
        "agentic rl",
        "automatic reward design",
        "batch reinforcement learning",
        "behavioral cloning",
        "bi-level reinforcement learning",
        "black-box reward optimization",
        "constrained reinforcement learning",
        "continual instruction tuning",
        "continual reinforcement learning",
        "continuous-time reinforcement learning",
        "convex reinforcement learning",
        "critique reinforcement learning",
        "cross-domain reinforcement learning",
        "curriculum learning",
        "deep reinforcement learning",
        "deep rl",
        "delayed reinforcement learning",
        "deterministic policy gradient",
        "direct preference optimization",
        "direct preference optimization (dpo)",
        "distributed reinforcement learning",
        "distributional reinforcement learning",
        "domain-specific sft",
        "double q-learning",
        "dpo",
        "druggability‑tailored preference optimization",
        "dual critic reinforcement learning",
        "erasable reinforcement learning",
        "flow actor-critic",
        "forgetting-augmented reinforcement learning",
        "generative adversarial imitation learning",
        "generative process reward model",
        "generative reward model",
        "goal-conditioned reinforcement learning",
        "group relative policy optimization (grpo)",
        "grpo",
        "heterogeneous agent reinforcement learning",
        "hierarchial reinforcement learning",
        "hierarchical reinforcement learning",
        "hierarchical rl",
        "hybrid rewards for reinforcement learning",
        "image reward model",
        "imitation learning",
        "imitation learning for robotics",
        "in-context reinforcement learning",
        "instruction tuning",
        "inverse reinforcement learning",
        "language model post-training",
        "llm fine-tuning (sft",
        "llm post-training",
        "llm sft",
        "meta reinforcement learning",
        "meta-reinforcement learning",
        "model based reinforcement learning",
        "model-based reinforcement learning",
        "model-based rl",
        "model-basedreinforcement learning",
        "multi agent reinforcement learning",
        "multi-agent imitation learning",
        "multi-agent reinforcement learning",
        "multi-objective reinforcement learning",
        "multi-objective reinforcement learning (morl)",
        "multi-task reinforcement learning",
        "multimodal process reward model",
        "multimodal reinforcement learning",
        "multimodal reward model",
        "non-stationary reinforcement learning",
        "off-policy rl",
        "off-policy rlvr",
        "offline goal-conditioned reinforcement learning",
        "offline imitation learning",
        "offline reinforcement learning",
        "offline rl",
        "offline safe reinforcement learning",
        "offline-to-online reinforcement learning",
        "on-policy",
        "on-policy actor-critic",
        "on-policy optimization",
        "on-policy sampling",
        "online dpo",
        "online reinforcement learning",
        "opponent shaping",
        "pluralistic reward modeling",
        "policy gradient",
        "policy gradient learning",
        "policy gradient methods",
        "policy gradients",
        "post-training",
        "post-training compression",
        "post-training quantization",
        "ppo",
        "preference based reinforcement learning",
        "preference learning",
        "preference optimization",
        "preference-based reinforcement learning",
        "process reward",
        "process reward model",
        "process reward modeling",
        "process reward models",
        "q-learning",
        "ranking and preference learning",
        "reinfocement learning with verifiable reward",
        "reinforcement learning",
        "reinforcement learning (rl)",
        "reinforcement learning fine-tuning",
        "reinforcement learning finetuning",
        "reinforcement learning for language models",
        "reinforcement learning for llms",
        "reinforcement learning from human feedback",
        "reinforcement learning from human feedback (rlhf)",
        "reinforcement learning from offline data",
        "reinforcement learning from verifiable rewards",
        "reinforcement learning from verifier rewards",
        "reinforcement learning specifications",
        "reinforcement learning theory",
        "reinforcement learning with human feedback",
        "reinforcement learning with human preference",
        "reinforcement learning with verifiable reward",
        "reinforcement learning with verifiable reward (rlvr)",
        "reinforcement learning with verifiable rewards",
        "reinforcement learning，image aesthetic assessment",
        "reward for reinforcement learning",
        "reward hacking",
        "reward hacking detection",
        "reward hacking prevention",
        "reward learning",
        "reward model",
        "reward modeling",
        "reward modeling as reasoning",
        "reward models",
        "reward shaping",
        "reward-free reinforcement learning",
        "risk-sensitive reinforcement learning",
        "rl finetuning",
        "rl finetuning of llms",
        "rl for llms",
        "rl from verifiable rewards",
        "rlaif",
        "rlhf",
        "rlhf training dynamics",
        "rlvr",
        "robot imitation learning",
        "robust reinforcement learning",
        "safe multi-agent reinforcement learning",
        "safe reinforcement learing",
        "safe reinforcement learning",
        "sample-efficient reinforcement learning",
        "self-imitation learning",
        "self-play",
        "self-play optimization",
        "sft",
        "skill-based reinforcement learning",
        "soft actor-critic (sac)",
        "stable reinforcement learning",
        "support constraint",
        "test-time reinforcement learning",
        "theory of reinforcement learning",
        "token-level policy gradients reshape",
        "tool-call reward model",
        "unsupervised reinforcement learning",
        "value function",
        "value function estimation",
        "value function factorization",
        "zero-shot reinforcement learning",
        "MDP",
        "POMDP",
        "Bandit",
        "Multi-armed bandit",
        "Contextual bandit",
        "Combinatorial multi-armed bandit",
        "Combinatorial semi-bandits",
        "Monte Carlo",
        "Temporal difference",
        "Bellman equation",
        "Advantage estimation",
        "Entropy regularisation",
        "Off-policy",
        "Policy optimisation",
        "Intrinsic motivation",
    ]
    kw_2 = [kw.lower() for kw in kw_2]
    len(kw_2)
    return (kw_2,)


@app.cell(hide_code=True)
def _():
    # List 3 – Inference Time Scaling & Optimization
    kw_3 = [
        "activation quantization",
        "adaptive compute",
        "attention-aware kv cache update",
        "auto think",
        "beam search",
        "best-of-n",
        "chain of thought",
        "chain of thoughts",
        "chain-of-thought",
        "chain-of-thought (cot)",
        "chain-of-thought prompting",
        "chain-of-thought reasoning",
        "compute budget allocation",
        "context parallel machenism",
        "cot",
        "cot monitoring",
        "cot reasoning",
        "early exit",
        "efficient llm inference",
        "generation chain-of-thought",
        "grounded chain-of-thought",
        "inference optimization",
        "inference scaling",
        "inference time",
        "inference time techniques",
        "inference-time adaptation",
        "inference-time algorithms",
        "inference-time alignment",
        "inference-time compute",
        "inference-time control",
        "inference-time improvement",
        "inference-time knowledge integration",
        "inference-time method",
        "inference-time optimization",
        "inference-time scaling",
        "interleaved chain-of-thought",
        "joint model compression",
        "kv cache",
        "kv cache compression",
        "kv cache eviction",
        "kv cache quantization",
        "kv cache retrieval",
        "kv cache subselection",
        "kv compression",
        "latent chain-of-thought",
        "layer-aware kv cache update",
        "llm decoding",
        "llm inference",
        "llm inference acceleration",
        "llm inference optimization",
        "long chain of thought",
        "long chain-of-thought",
        "long cot distillation",
        "long cots",
        "long-cot reasoning",
        "majority voting",
        "model compression",
        "model quantization",
        "multi-modal chain-of-thought",
        "multimodal interleaved chain-of-thought (cot)",
        "multimodal large language model；chain-of-thought",
        "parallel decoding",
        "post training quantization",
        "post-training quantization",
        "quantization",
        "reasoning scaling",
        "scaling test-time compute",
        "self-consistency",
        "soft best-of-n",
        "soft-best-of-n",
        "spatial chain-of-thought",
        "speculative decoding",
        "test time compute",
        "test time scaling",
        "test-time compute",
        "test-time scaling",
        "unfaithful chain-of-thought",
        "vector-quantization",
        "visual chain of thought",
        "sampling",
        "Top-k sampling",
        "Top-p",
        "Nucleus sampling",
        "Contrastive decoding",
        "Batch decoding",
        "GPTQ",
    ]
    kw_3 = [kw.lower() for kw in kw_3]
    len(kw_3)
    return (kw_3,)


@app.cell(hide_code=True)
def _():
    # List 4 – Infrastructure
    kw_4 = [
        "activation checkpointing",
        "batch size",
        "batch size scheduling",
        "cloud computing",
        "continual pretraining",
        "critical batch size",
        "distributed system",
        "distributed systems",
        "distributed training",
        "efficient training",
        "expert offloading",
        "federated fine-tuning",
        "federated learning",
        "fsdp",
        "gpu-parallel optimization",
        "gradient checkpointing",
        "gradient compression",
        "hardware acceleration",
        "hardware-efficient attention",
        "hierarchical federated learning",
        "knowledge offloading",
        "learning rate schedule",
        "learning rate schedules",
        "llm pretraining",
        "memory efficient training",
        "memory-efficient training",
        "ml system",
        "muon optimizer",
        "offloading",
        "one-shot federated learning",
        "optimal batch size",
        "parameter server",
        "parameter-efficient training",
        "personalized federated fine-tuning",
        "riemannian federated learning",
        "semi-supervised federated learning",
        "sequence parallelism",
        "training efficiency",
        "vertical federated learning",
        "GPU",
        "GPUs",
        "GPU kernel",
        "Triton kernel",
        "Cuda kernels",
        "Distributed computing",
        "Distributed computing",
        "Checkpoint merging",
        "Parallelism",
        "Task parallelism",
    ]
    kw_4 = [kw.lower() for kw in kw_4]
    len(kw_4)
    return (kw_4,)


@app.cell(hide_code=True)
def _():
    # List 5 – AI Safety, Governance & Ethics
    kw_5 = [
        "accountability",
        "adversarial robustness",
        "ai alignment",
        "ai fairness",
        "ai privacy",
        "ai risk",
        "ai safety",
        "ai safety and security",
        "ai truthfulness and deception",
        "aigc copyright protection",
        "aigc watermarking",
        "algorithmic fairness",
        "applications of interpretability",
        "automated interpretability",
        "benchmarking interpretability",
        "bias and fairness",
        "bias detection",
        "black-box jailbreak",
        "black-box watermark",
        "brain–ai alignment",
        "chain-of-thought interpretability",
        "cognitive interpretability",
        "concept-based explainability",
        "content moderation",
        "copyright",
        "copyright protection",
        "counterfactuality",
        "data privacy",
        "data privacy in generative models",
        "dataset copyright protection",
        "deception",
        "deepfake detection",
        "deepfakes",
        "deepfakes attribution",
        "democratic ai alignment",
        "developmental interpretability",
        "differential privacy",
        "digital asset watermarking",
        "digital watermark",
        "digital watermarking",
        "emotion hallucination",
        "ethical ai",
        "explainability",
        "explainability ai",
        "factuality",
        "factuality evaluation",
        "fairness",
        "fairness auditing",
        "fairness benchmark",
        "fairness in machine learning",
        "fairness-accuracy tradeoff",
        "fake news",
        "green ai",
        "guardrail",
        "guardrails",
        "hallucination",
        "hallucination and confabulation",
        "hallucination control",
        "hallucination detection",
        "hallucination in vision language model",
        "hallucination mitigation",
        "hallucinations",
        "hate speech detection",
        "human-ai alignment",
        "human–ai alignment",
        "image watermark",
        "indirect prompt injection",
        "individualized differential privacy",
        "intellectual property",
        "intellectual property protection",
        "interpretability",
        "interpretability and analysis",
        "interpretability and explainable ai",
        "interpretability of neural networks",
        "interpretability techniques",
        "intrinsic interpretability",
        "jailbreak",
        "jailbreak attack",
        "jailbreak attacks",
        "jailbreak defense",
        "jailbreak detection",
        "jailbreak guard",
        "jailbreaking",
        "jailbreaking attacks",
        "jailbreaks",
        "label misinformation",
        "language model interpretability",
        "llm deception",
        "llm hallucination",
        "llm interpretability",
        "llm response factuality",
        "llm safety",
        "llm watermarking",
        "local differential privacy",
        "long-form hallucination",
        "mechanism interpretability",
        "mechanistic interpretability",
        "membership inference attack",
        "membership inference attacks",
        "misinformation",
        "mitigating hallucination",
        "mllm hallucination",
        "model analysis & interpretability",
        "model explainability",
        "model interpretability",
        "model safety",
        "multimodal misinformation detection",
        "pluralistic ai alignment",
        "prompt injection attack",
        "prompt injection attacks",
        "prompt injections",
        "re-watermarking",
        "red teaming",
        "relational hallucination",
        "relative value learning",
        "robust fairness",
        "safety alignment",
        "semantic-level watermark",
        "social impact",
        "structure hallucination",
        "text watermark",
        "top-down interpretability",
        "trustworthy",
        "trustworthy ai",
        "trustworthy llms",
        "trustworthy machine learning",
        "truthfulness",
        "utility-fairness trade-off",
        "value alignment",
        "visual hallucination snowballing",
        "watermark",
        "watermark-based attribution",
        "watermarking",
        "watermarks",
        "white-box jailbreak",
        "Adversarial attacks",
        "Adversarial examples",
        "Adversarial training",
        "Data poisoning",
        "Data poisoning attack",
        "Poisoning attacks",
        "Backdoor attack",
        "Backdoor defence",
        "Backdoor training",
        "Finetuning data stealing",
        "Membership inference",
    ]
    kw_5 = [kw.lower() for kw in kw_5]
    len(kw_5)
    return (kw_5,)


@app.cell(hide_code=True)
def _():
    # List 6 – AI for Science & Life Sciences
    kw_6 = [
        "3d medical image analysis",
        "3d molecular generation",
        "3d molecule generation",
        "ai for biology",
        "ai for healthcare",
        "ai for materials",
        "ai for metascience",
        "ai for physics",
        "ai for science",
        "ai4biology",
        "alphafold3",
        "alternating exposures",
        "alternating gradient descent-ascent",
        "applications to drug discovery",
        "atomistic protein design",
        "automated scientific discovery",
        "biology",
        "biology experimental operation",
        "biology foundation model",
        "brain decoding",
        "cancer patient",
        "cancer survival prediction",
        "cardiac diagnosis",
        "cell biology",
        "chemistry",
        "clinical",
        "clinical decision making",
        "clinical inquiry",
        "clinical natural language processing",
        "clinical reasoning",
        "computational neuroscience",
        "computational pathology",
        "computer aided diagnosis",
        "computer vision for healthcare",
        "convolution alternatives",
        "coupled physics simulation",
        "cryo-em",
        "data-driven scientific discovery",
        "deep learning for health",
        "deficiency diagnosis",
        "diffusion models for computational chemistry",
        "digital pathology",
        "drug discovery",
        "efficient medical segmentation",
        "ehealth",
        "electronic health records",
        "electronic medical record",
        "evolutionary biology",
        "external memory",
        "external validity",
        "fault diagnosis",
        "fluid dynamics",
        "fmri",
        "fmri decoding",
        "fmri prediction",
        "fmri-to-image reconstruction",
        "fragment-based drug design",
        "fragment-based drug discovery",
        "functional magnetic resonance imaging (fmri)",
        "gene expression prediction",
        "generative chemistry",
        "genome",
        "genomics",
        "healthcare",
        "histopathology image representation learning",
        "internal signal",
        "learnability",
        "learnable compression",
        "learnable fractional superlets",
        "learnable non-uniform dft",
        "llm-based drug discovery",
        "machine learning for healthcare",
        "materials science",
        "medical",
        "medical agent",
        "medical agents",
        "medical ai",
        "medical ai evaluation",
        "medical benchmark",
        "medical diagnosis",
        "medical dialogue",
        "medical foundation model",
        "medical generative pre-trained models",
        "medical image",
        "medical image analysis",
        "medical image classification",
        "medical image generation",
        "medical image segmentation",
        "medical imaging",
        "medical imaging analysis",
        "medical literature",
        "medical mllm",
        "medical multi-modal alignment",
        "medical multimodal benchmark",
        "medical multimodal large language model",
        "medical question answering",
        "medical reasoning",
        "medical segmentation",
        "medical time seris",
        "medical ultrasound",
        "medical visual question answering",
        "medical visual reasoning",
        "medical vlm",
        "medical vqa",
        "mental health",
        "molecular dynamics",
        "molecular generation",
        "molecular property prediction",
        "molecule generation",
        "multi-modal diagnosis",
        "multi-scale protein structure",
        "multimodal medical benchmark",
        "multimodal medical reasoning",
        "neural decoding",
        "neuroscience",
        "organic reaction prediction",
        "pan-cancer modeling",
        "pan-cancer screening",
        "physics simulation",
        "physics simulations",
        "policy internalization",
        "pre-trained protein language model",
        "protein design",
        "protein language model",
        "protein language modeling",
        "protein language models",
        "protein structure",
        "protein structure generation",
        "protein structure modeling",
        "protein structure prediction",
        "protein structure refinement",
        "quantum computing",
        "radiology",
        "radiology report generation",
        "rna design",
        "rna foundation model",
        "rna inverse design",
        "rna non-canonical base pair",
        "rna secondry structure prediction",
        "rna structure",
        "rnn transformer alternatives",
        "scientific discovery",
        "scrna-seq",
        "single cell",
        "single cell genomics",
        "single-cell biology",
        "single-cell genomics",
        "single-cell rna sequencing",
        "structural bioinformatics",
        "structural biology",
        "structure based drug design",
        "surrogate gradient alternatives",
        "synthesizable drug design",
        "ternarization",
        "ternary quantization",
        "unlearnable examples",
        "visual neural decoding",
        "Environmental science",
        "Machine learning in environmental science",
        "Climate",
        "Climate change",
        "Climate downscaling",
        "Energy efficiency",
        "Energy saving",
        "Carbon sequestration",
        "Material discovery",
        "Material generation",
        "Material identification",
        "Material property prediction",
        "Differentiable physics",
        "Geophysics",
        "Quantum",
        "Quantum algorithms",
        "Quantum machine learning",
        "Quantum neural networks",
        "Quantum information",
        "Quantum deep learning",
        "Quantum physics",
        "Variational quantum eigensolver",
        "Molecular docking",
    ]
    kw_6 = [kw.lower() for kw in kw_6]
    len(kw_6)
    return (kw_6,)


@app.cell(hide_code=True)
def _():
    # List 7 – Physical AI & Robotics
    kw_7 = [
        "3d manipulation",
        "autonomous vehicles",
        "bimanual manipulation",
        "bimanual mobile manipulation",
        "data generation for robot learning",
        "dexterous grasping",
        "dexterous hand",
        "dexterous manipulation",
        "drag-style manipulation",
        "dual-arm robots",
        "dynamic tactile perception",
        "efficient robot reasoning",
        "efficient robotic manipulations",
        "embodied agent",
        "embodied agents",
        "embodied ai",
        "embodied intelligence",
        "embodied memory",
        "embodied navigation",
        "embodied reasoning",
        "embodied urban navigation",
        "foundation models based robot manipulation",
        "general robotic manipulation",
        "generalist robot policies",
        "generalist robot policy",
        "generalizable grasping",
        "hand manipulation synthesis",
        "heterogeneous tactile data",
        "humanoid",
        "humanoid control",
        "humanoid locomotion",
        "humanoid robot",
        "humanoid robots",
        "image manipulation localization",
        "imitation learning for robotics",
        "key-value cache manipulation",
        "learning robotic policies from videos",
        "llms for robotics",
        "locomotion",
        "locomotion and manipulation",
        "long-horizon manipulation",
        "manipulation",
        "manipulation video",
        "mobile manipulation",
        "motion planning",
        "mujoco benchmarks",
        "multi-joint robot locomotion",
        "multi-modal embodied agent",
        "multi-robot cooperation",
        "real-to-sim",
        "real-to-sim-to-real",
        "robot co-design",
        "robot data generation",
        "robot datasets and benchmarking",
        "robot foundation model",
        "robot hands",
        "robot imitation learning",
        "robot learning",
        "robot learning，forward dynamics，inverse dynamics",
        "robot manipulation",
        "robot navigation",
        "robot planning",
        "robot policy learning",
        "robot simulation",
        "robot skill acquisition",
        "robot task planning",
        "robotic foundation models",
        "robotic manipulation",
        "robotic tool use",
        "robotics",
        "robotics evaluation",
        "robotics foundation model",
        "robotics learning",
        "robotics manipulation",
        "robotics planning",
        "robotics policy",
        "robots",
        "sim-to-real",
        "sim-to-real matching",
        "streaming video manipulation",
        "tactile",
        "tactile dataset",
        "tactile representation learning",
        "tactile sensing",
        "task and motion planning",
        "text image manipulation",
        "uav",
        "uav-based search and rescue",
        "video manipulation localization",
        "vision-based robotics",
        "vision-proprioception policy",
        "whole-body control",
        "zero-shot robotic manipulation",
        "zero-shot sim2real",
        "SLAM",
        "Dense semantic SLAM",
        "Localisation",
        "Planning",
        "Path planning",
        "Dynamic path planning",
        "Domain randomisation",
    ]
    kw_7 = [kw.lower() for kw in kw_7]
    len(kw_7)
    return (kw_7,)


@app.cell(hide_code=True)
def _():
    # List 8 – Media, Video, Games & Music
    kw_8 = [
        "3d avatar",
        "3d avatar modeling",
        "3d diffusion model",
        "3d generative models",
        "3d-aware video generation",
        "4d video generation and editing",
        "animation",
        "atari",
        "audio and music generation",
        "audio generation",
        "audio-to-video generation",
        "auto-regressive image generation",
        "auto-regressive video generation",
        "autoregressive image generation",
        "autoregressive video generation",
        "avatar",
        "board games",
        "camera-controllable video generation",
        "camera-guided video generation",
        "causal text to video generation",
        "character animation",
        "chess",
        "coherent video generation",
        "conditional diffusion model",
        "conditional diffusion models",
        "conditional image generation",
        "continuous image generation",
        "controllable hand image generation",
        "controllable image generation",
        "controllable image synthesis",
        "controllable speech synthesis",
        "controllable video diffusion models",
        "controllable video editing",
        "controllable video generation",
        "creative writing",
        "denoising diffusion models",
        "diffusion model",
        "diffusion model alignment",
        "diffusion models",
        "discrete diffusion model",
        "discrete diffusion models",
        "efficient autoregressive image generation",
        "efficient video generation",
        "efficient video understanding",
        "facevideo editing",
        "filmmaking",
        "first-last frame video generation",
        "game ai",
        "game generative ai models",
        "game playing",
        "game reasoning",
        "games",
        "gaming",
        "gaussian avatar",
        "generative video models",
        "high-resolution text-to-video generation",
        "human animation",
        "human video generation",
        "image and video generation",
        "image generation",
        "image generation benchmark",
        "image generation model unlearning",
        "image synthesis",
        "infinite-length video generation",
        "instruction-guided video editing",
        "interactive video generation",
        "interleaved text and image generation",
        "interpretable diffusion model",
        "joint audio-video generation",
        "keyframe narratives",
        "latent diffusion model",
        "latent diffusion models",
        "long video generation",
        "long video understanding",
        "long-video understanding",
        "mask diffusion model",
        "masked diffusion model",
        "masked diffusion models",
        "minecraftocc dataset",
        "mobile video generation",
        "movie scene boundary detection",
        "multi-person interactive video generation",
        "multi-shot video generation",
        "multi-track music generation",
        "multi-view diffusion model",
        "multi-view diffusion models",
        "music generation",
        "narrative coherence",
        "narrative modeling",
        "narratives",
        "online ultra-long video understanding",
        "online video understanding",
        "pixel diffusion model",
        "portrait animation",
        "pose-free animation",
        "real-time video generation",
        "relation aware text-to-audio generaion",
        "scene-consistent video generation",
        "score-based diffusion model",
        "score-based diffusion models",
        "score-based generative models",
        "shortcut diffusion models",
        "sounding video generation",
        "speech generation",
        "speech synthesis",
        "stable diffusion model",
        "story generation",
        "streaming video understanding",
        "subject-consistent image generation",
        "subject-driven image generation",
        "talking person video generation",
        "text diffusion model",
        "text to image synthesis",
        "text to video generation",
        "text-to-audio-video generation",
        "text-to-image",
        "text-to-image diffusion model",
        "text-to-image diffusion models",
        "text-to-image generation",
        "text-to-image generative evaluation",
        "text-to-image models",
        "text-to-image synthesis",
        "text-to-speech",
        "text-to-speech (tts)",
        "text-to-speech synthesis",
        "text-to-video",
        "text-to-video dataset",
        "text-to-video generation",
        "ultra-long video synthesis",
        "video compression",
        "video diffusion",
        "video diffusion acceleration",
        "video diffusion model",
        "video diffusion models",
        "video diffusion transfer",
        "video editing",
        "video generation",
        "video generation models",
        "video generative model",
        "video model",
        "video modeling",
        "video models",
        "video understanding",
        "video understanding & activity analysis",
        "video-to-audio generation",
        "world2minecraft",
        "TTS",
        "AI for music",
        "Audio coding",
        "Audio comprehension",
        "Audio editing",
        "Audio inpainting",
        "Audio language model",
        "Sound separation",
        "Image-grounded video perception and reasoning",
        "Universal sound separation",
        "Sound source localisation",
    ]
    kw_8 = [kw.lower() for kw in kw_8]
    len(kw_8)
    return (kw_8,)


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    # 2. Load
    """)
    return


@app.cell
def _():
    df = pl.read_parquet("iclr_2026_scored.parquet")
    print(f"Loaded {df.shape[0]} rows × {df.shape[1]} columns")
    return (df,)


@app.cell
def _(df):
    df
    return


@app.cell(hide_code=True)
def _():
    mo.md(r"""
    ## 2.1 Filter by keywords
    """)
    return


@app.cell
def _(df, kw_1):
    df_1 = df.filter(pl.col("keywords").list.eval(pl.element().str.to_lowercase().is_in(kw_1)).list.any())
    df_1
    return


@app.cell
def _(df, kw_2):
    df_2 = df.filter(pl.col("keywords").list.eval(pl.element().str.to_lowercase().is_in(kw_2)).list.any())
    df_2
    return


@app.cell
def _(df, kw_3):
    df_3 = df.filter(pl.col("keywords").list.eval(pl.element().str.to_lowercase().is_in(kw_3)).list.any())
    df_3
    return


@app.cell
def _(df, kw_4):
    df_4 = df.filter(pl.col("keywords").list.eval(pl.element().str.to_lowercase().is_in(kw_4)).list.any())
    df_4
    return


@app.cell
def _(df, kw_5):
    df_5 = df.filter(pl.col("keywords").list.eval(pl.element().str.to_lowercase().is_in(kw_5)).list.any())
    df_5
    return


@app.cell
def _(df, kw_6):
    df_6 = df.filter(pl.col("keywords").list.eval(pl.element().str.to_lowercase().is_in(kw_6)).list.any())
    df_6
    return


@app.cell
def _(df, kw_7):
    df_7 = df.filter(pl.col("keywords").list.eval(pl.element().str.to_lowercase().is_in(kw_7)).list.any())
    df_7
    return


@app.cell
def _(df, kw_8):
    df_8 = df.filter(pl.col("keywords").list.eval(pl.element().str.to_lowercase().is_in(kw_8)).list.any())
    df_8
    return


@app.cell
def _():
    return


if __name__ == "__main__":
    app.run()
